#pragma once
#include <map>
#include <vector>
#include <string>
#include <random>

class MockRepository
{
public:
	MockRepository(){}

	// Constructs a POST request
	std::string ConstructMessagePoster();

	// Constructs a LIST or COUNT request
	std::string ConstructMessageReader();

private:
	// randomise a number rangewise
	unsigned int RandomRange(unsigned int min, unsigned int max);
	
	// 13 politicians who are active on twitter
	std::map<std::string, unsigned int> topicIds = {{"realDonaldTrump", 0},
	 {"BarackObama", 0},
	 {"EmmanuelMacron", 0},
	 {"MLP_officiel", 0},
	 {"LeoVaradkar", 0},
	 {"GerryAdamsSF", 0},
	 {"BorisJohnson", 0},
	 {"jeremycorbyn", 0},
	 {"OlafScholz", 0},
	 {"matteosalvinimi", 0},
	 {"vonderleyen", 0},
	 {"MaireadMcGMEP", 0},
	 {"EP_President", 0}};
	
	// Each user has 13 tweets (as messages) (tweets as of 07/01/2020)
	std::vector<std::string> messages = {
		// realDonaldTrump
		"Great interview with @GOPLeader Kevin McCarthy on @foxandfriends. \"There was no urgency with the Articles of Impeachment because there was no case.\"",
		"We love Australia!",
		"Amazing analysis & reporting!",
		"....If however, the city or state in question is willing to acknowledge responsibility, and politely asks for help from the Federal Government, we will very seriously consider getting involved in order to make those poorly run Democrat Cities Great Again!",
		"The homeless situation in Los Angeles, San Francisco, and many other Democrat Party run cities throughout the Nation is a state and local problem, not a federal problem....",
		"IRAN WILL NEVER HAVE A NUCLEAR WEAPON!",
		"Congress & the President should not be wasting their time and energy on a continuation of the totally partisan Impeachment Hoax when we have so many important matters pending. 196 to ZERO was the Republican House vote, & we got 3 Dems. This was not what the Founders had in mind!",
		"The Impeachment Hoax, just a continuation of the Witch Hunt which started even before I won the Election, must end quickly. Read the Transcripts, see the Ukrainian President’s strong statement, NO PRESSURE - get this done. It is a con game by the Dems to help with the Election!",
		"\"The reason they are not sending the Articles of Impeachment to the Senate is that they are so weak and so pathetic.\" @LindseyGrahamSC @MariaBartiromo  The great Scam continues. To be spending time on this political Hoax at this moment in our history, when I am so busy, is sad!",
		"These Media Posts will serve as notification to the United States Congress that should Iran strike any U.S. person or target, the United States will quickly & fully strike back, & perhaps in a disproportionate manner. Such legal notice is not required, but is given nevertheless!",
		"The United States just spent Two Trillion Dollars on Military Equipment. We are the biggest and by far the BEST in the World! If Iran attacks an American Base, or any American, we will be sending some of that brand new beautiful equipment their way...and without hesitation!",
		"They attacked us, & we hit back. If they attack again, which I would strongly advise them not to do, we will hit them harder than they have ever been hit before!",
		"....targeted 52 Iranian sites (representing the 52 American hostages taken by Iran many years ago), some at a very high level & important to Iran & the Iranian culture, and those targets, and Iran itself, WILL BE HIT VERY FAST AND VERY HARD. The USA wants no more threats!",
		// BarackObama
		"With David Stern’s passing, I’m reflecting on everything he did to take the NBA global, creating entire new generations of fans pretending to be like Mike or any of their favorite players on driveways and playgrounds around the world.",
		"Here’s to a happy, healthy, and hopeful 2020. Happy New Year, everybody!",
		"From hip-hop to country to The Boss, here are my songs of the year. If you’re looking for something to keep you company on a long drive or help you turn up a workout, I hope there’s a track or two in here that does the trick.",
		"If there’s one thing I love about @RepJohnLewis, it’s his incomparable will to fight. I know he’s got a lot more of that left in him. Praying for you, my friend.",
		"Next up are my favorite movies and TV shows of 2019. Of course, there’s also American Factory, a film from our own production company, Higher Ground, that was recently shortlisted for an Oscar. Here’s the full list:",
		"As we wind down 2019, I wanted to share with you my annual list of favorites that made the last year a little brighter. We’ll start with books today — movies and music coming soon. I hope you enjoy these as much as I did.",
		"From the Obama family to yours, Merry Christmas!",
		"On behalf of my family, Chag Sameach and Happy Hanukkah! As Jews around the world celebrate, let the menorah’s light remind us all of the miracles in our own lives.",
		"2019 was full of moments that show humanity at its best—compassionate, entrepreneurial, determined. And yes, hopeful. Take a look to see for yourself.",
		"You can get the zen garden next week, but tomorrow is the last day to sign up for health coverage at http://HealthCare.gov. This year, most current http://HealthCare.gov customers can find an insurance plan with a monthly premium of $10 or less. Get covered today!",
		"It was remarkable to be back in the Asia-Pacific region with my sister this week, joined by hundreds of talented and optimistic @ObamaFoundation leaders. They’re making their mark on this region—and the whole world—and that's good for all of us.",
		"My sister Maya and I are about to take the stage at @ObamaFoundation Leaders: Asia-Pacific. We'll be talking about how growing up in this region made us who we are—and the opportunity today's young people have to shape the future. I hope you'll tune in at",
		"I thought it was about time I share my holiday gift list — a few practical items, all $10 or less. The best one? Health care for you or somebody you care about. The deadline to sign up is December 15. Go to http://HealthCare.gov and get covered.",
		// EmmanuelMacron
		"Vœux 2020 aux Français.",
		"Il y a cinq ans, l’horreur terroriste et le crime antisémite frappaient la République. Pensées pour toutes les victimes de Charlie Hebdo, de l’Hypercacher et pour les policiers lâchement assassinés. Solidarité avec leurs familles et leurs proches. Nous n’oublierons jamais.",
		"I express our solidarity with the Australian people in the face of wildfires that are currently ravaging their country. I called @ScottMorrisonMP this morning to offer immediate French operational assistance to fight fires, protect affected population and preserve biodiversity.",
		"Solidarité avec le peuple australien face aux incendies qui ravagent leur pays. Ce matin, j’ai appelé @ScottMorrisonMP pour offrir notre aide opérationnelle immédiate pour lutter contre les feux, protéger la population et préserver la biodiversité.",
		"la souveraineté et la sécurité de l’Irak, ainsi que la stabilité de la région ; la lutte contre le terrorisme de Daech. Rien ne doit nous détourner de ces objectifs. (2/2)",
		"L’escalade des tensions au Moyen-Orient n’est pas une fatalité. La France a deux priorités que je partage avec l’ensemble des dirigeants concernés que je contacte : (1/2)",
		"L’année s’ouvre endeuillée par le drame de Villejuif. J’adresse mon soutien aux victimes de l’attaque, à leurs familles ainsi qu’aux forces de l’ordre. Nous poursuivons avec détermination la lutte contre la violence aveugle et notre combat pour la sécurité de tous les Français.",
		"Très bonne année 2020",
		"Ensemble, faisons de la décennie qui s’ouvre une décennie française et européenne.",
		"2020 sera l’année où un nouveau modèle écologique doit se déployer.",
		"L'apaisement toujours, doit primer sur l'affrontement.",
		"Un projet de justice et de progrès social.",
		"La réforme des retraites est un projet de justice et de progrès social qui sera mené à son terme. Mais j’entends les peurs qui se font jour. Pour vous, avec les organisations syndicales qui le veulent, j’attends du Gouvernement qu’il trouve la voie d’un compromis rapide.",
		// MLP_officiel
		"Note qui n’empêche pas #Blackrock de déclarer dans un communiqué le 2 janvier : \"En aucune manière, nous n'avons cherché à exercer une influence sur la réforme du système de retraite par répartition en cours auprès des pouvoirs publics ou de tout autre acteur du secteur\" ! MLP",
		"Étonnante, cette note adressée au gouvernenent ? Je croyais que M. Cirelli avait déclaré que l’épargne-retraite n’intéressait pas #BlackRock ? MLP #RéformeDesRetraites https://www.blackrock.com/corporate/literature/whitepaper/viewpoint-loi-pacte-le-bon-plan-retraite-juin-2019.pdf ...",
		"Sérieusement, quelles décisions nouvelles ont été prises depuis 5 ans en matière de lutte contre le terrorisme islamiste ? Quelles actions majeures depuis le massacre de Charlie Hebdo et de l’Hyper Cacher ? AUCUNE. MLP",
		"Mais qu’attend Emmanuel #Macron pour prendre la mesure de la terrible menace qui pèse sur nos compatriotes et mener une guerre totale au fondamentalisme islamiste ? MLP #Metz",
		"Des heures et des heures de débats psychiatrisants avec plein d’« experts » et de « sachants », et pas un mot sur la victime, sur sa femme, sur les blessés graves... Inquiétante société que la nôtre ! MLP #Villejuif",
		"Nous ne sommes qu'au début de l'année, et déjà notre pays déplore une attaque terroriste ayant fait un mort et deux blessés graves à #Villejuif. Merci à nos forces de l'ordre qui ont neutralisé ce qui ressemble fort à un islamiste, avec sang-froid et détermination. MLP",
		"Après la mort de #Souleimani, qui sonne comme avertissement du Président Trump à l’#Iran, la France doit continuer à parler à tous les acteurs et participer par tous les moyens dont elle dispose à relancer les négociations. 🖋 Mon communiqué :",
		"« #VoeuxMacron2020 : Macron fait du Macron » ✍🏻 Retrouvez ma réaction aux vœux présidentiels :",
		"Je vous souhaite à tous une bonne et heureuse année 2020. J’ai une pensée particulière pour nos pompiers, militaires, policiers et personnels médicaux mobilisés en ce jour de fête. Que 2020 soit pour notre pays tant divisé l’année de l’unité et de l’espérance !MLP",
		"Une fois de plus... rien. MLP #VoeuxMacron2020",
		"📹 Je vous souhaite à tous un très #JoyeuxNoël, avec une pensée affectueuse et chaleureuse pour ceux qui sont confrontés à la solitude, à la maladie ou au dénuement. Je souhaite à la France de retrouver les voies de l'unité, de la concorde et de la fraternité. 🎄",
		"Joyeuse préparation de Noël à tous et pensée affectueuse à ceux qui ce soir travailleront pour assurer notre bien-être et notre sécurité. MLP",
		"Les dealers et les mafias, eux, ne font pas la grève des confiseurs ! Et toujours zéro interpellation... Nos policiers sont les premières victimes de leur hiérarchie politique, le peuple est la deuxième.MLP",
		// LeoVaradkar
		"We should respect all traditions on our island and be mature enough as a State to acknowledge all aspects of our past.",
		"The RIC/DMP commemoration is not a celebration. It’s about remembering our history, not condoning what happened. We will also remember the terrible burning of Cork, Balbriggan, partition and the atrocities of the Civil War.",
		"Thanked @IrishCoastGuard chief this morning for the vital work of his teams off Wexford in very difficult circumstances, plus the other volunteers. Our thoughts are with family and friends of the missing fisherman, and his colleague, as the search continues.",
		"Opposition parties disagree. They are calling for more tax, more spending and more borrowing. That’s the road back to austerity. Let’s not let them to do that to us again",
		"Running a surplus makes sense as it creates a buffer against any fall in the tax take from the profits of multi-nationals. Experts say this is inevitable once global tax rules change",
		"The surplus is being used to reduce our national debt which in turn means lower interest repayments, which frees up money we can spend on schools, healthcare and housing in a sustainable way",
		"Today’s figures show the Government recorded a Budget surplus of €1.4bn or 0.4% of GDP in 2019. This was better than expected on Budget Day and means that for two years in a row we are taking in more revenue than we are spending",
		"Govt is totally committed to the Cork Events Centre. Delays aren’t good enough. However, it’s going to be worth it for a much bigger better project than originally envisaged",
		"The lesser known Marian Finucane. The architect, activist and proud Dublin woman: RTÉ Archives | Arts and Culture | Marian Finucane as a Student Protester",
		"I spent many hours in the studio with Marian. She was thorough, courteous and professional. I’m very sad to think that we won’t hear her voice again on the radio. The deepest sympathies of the Irish Government to her family, friends and colleagues.",
		"I am stunned and deeply saddened to hear of the death of Marian Finucane. She was a true broadcasting legend who reshaped current affairs radio. Ireland will miss her voice. Weekend mornings will never be quite the same again.",
		"Will be pleased to have @sebastiankurz back at @EUCouncil as Austrian Chancellor. He will head Europe’s first coalition involving an @EPP party and a Green Party",
		"I know it’s not enough. Which is why with certainty on Brexit, a well-managed economy and the public finances back in surplus, we can do much better in the next Budget",
		// GerryAdamsSF
		"Nollaig na mBan faoi mhaise daoibh. And my daughters will have daughters as strong as were their mothers. And my four green fields will bloom once again said she.",
		"Go raibh maith agat Jonathan.",
		"Awhh D!",
		"My condolences to Marian Finucane’s family, her collegues and friends. Mo comhbhrón daoibhse go leir.",
		"Floorboards was my friend. Sorry. Floorboards is my friend. I don't believe that your friends cease to be your friends just because they die. No, they are still your friends. So with Floorboards. https://shar.es/a3J9gr",
		"Gerry Adams TD extends condolences on death of Brendan Ó Cathaoir – A courageous voice https://www.sinnfein.ie/contents/55641",
		"#backfromthebrink . A great clar on RTE1. Well done Derek Mooney & crew.",
		"Lá breithe shona duit Eolan",
		"Comhghdeardas Deirdre agus míle buiochas Máirtín agus Helen s bhur gclann. xo",
		"Go raibh maith agat Seán Downes.",
		"Me & Joe Magee in Dublin over 50 years ago. Im the one with the glasses.",
		"Daoibhse fosta Mark agus Casey & clann.",
		"A slightly out off focus Lon dubh ag canadh go milis ar son Chriost.",
		// BorisJohnson
		"We are going to unite and level up, bringing the whole of this incredible United Kingdom - England, Scotland, Wales, Northern Ireland - together.",
		"Our hearts go out to all those in Australia affected by these devastating fires. I have been in touch with PM @ScottMorrisonMP to offer any assistance we can provide. We stand with you at this very difficult time. 🇬🇧🇦🇺",
		"This is going to be a fantastic year for Britain.",
		"Happy New Year! Let’s make 2020 a fantastic year for Britain.",
		"We are going to level up and unite our country. We are going to get Brexit done and deliver the change that people voted for. And we are going to protect and invest in our amazing NHS.",
		"We are going to legislate for the biggest investment in our NHS in living memory.",
		"We will be out of the EU on 31st January. We will invest billions more in our NHS. We will level up and unite our country. #PeoplesGovernment",
		"We are going to get Brexit done and unite our fantastic country.",
		"Wishing you and your family a very Merry Christmas🎄",
		"Whoever you are, wherever you are, and however you’re celebrating, have a very happy Christmas, and I’ll see you all again in the New Year.",
		"Thank you to all the NHS staff who work so hard to take care of us, especially over the Christmas period.",
		"Thank you very much to our Armed Forces for everything you do, you represent the best of our country, and happy Christmas!",
		"Britain would not be Britain without its Jewish community. And we will stand with you and celebrate with you - at Chanukah and all year round.",
		// jeremycorbyn
		"My thoughts are with those who lost their loved ones and their homes in the devastating Australian fires. As our planet is ravaged by firesand floods, evidence of the climate emergency couldn’t be clearer.We need immediate action to save our planet.",
		"This is grotesque.",
		"Foreign Secretary Dominic Raab’s declaration of ‘sympathy' for Trump’s reckless and lawless killing of Iranian general Qassem Suleimani is craven and dangerous. Boris Johnson’s government must oppose this escalation towards another devastating war in the Middle East.",
		"Two days since I asked Boris Johnson these vital questions about the US assassination of Qasem Soleimani and its consequences. And no answer.",
		"I'm shocked by the senseless murder of a food delivery driver in Finsbury Park. My thoughts are with his loved ones and the Algerian community. The attacker must be brought to justice. And more must be done to protect delivery drivers who have such unsafe working conditions.",
		"I've written to Boris Johnson requesting an urgent Privy Council briefing and answers to questions following the US assassination of Qassem Suleimani.",
		"The US assassination of Qasem Soleimani is an extremely serious and dangerous escalation of conflict with global significance. The UK government should urge restraint on the part of both Iran and the US, and stand up to the belligerent actions and rhetoric coming from the US.",
		"Today's average fare increase means ticket prices have risen by 40% since 2010. Yet the Tory Transport Secretary, Grant Shapps, says the government is \"putting passengers first\". 🤔",
		"We’re up for the fight. To protect what we hold dear. #HappyNewYear2020",
		"We're not broke, we're being robbed.",
		"How terrible that Chanukah started with a message of hope and on this last day we face antisemitic graffiti in London and horrific stabbings at a party in New York. We stand with all our communities facing hate. We send love and solidarity to Jewish communities around the world.",
		"The far right is on the rise, emboldened by a prime minister who has divided our communities. We will never let them win.",
		"Boris Johnson pledged in the election that the NHS was not for sale. He has already broken that promise.",
		// OlafScholz
		"Felicidades @sanchezcastejon! Herzlichen Glückwunsch an Pedro Sánchez zu seiner Wahl als Ministerpräsident #Spanien|s. Die #Sozialdemokratie lebt! @PSOE #España @spdde",
		"Manfred Stolpe war eine große Persönlichkeit - mit Ecken und Kanten, integer, warmherzig, klug. Er verstand sich stets als Brückenbauer und Versöhner. Die SPD verliert mit ihm einen aufrechten Sozialdemokraten, der Osten eine wichtige Stimme, Brandenburg einen großen Politiker.",
		"Frohe #Weihnachten! Ich wünsche allen schöne Festtage im Kreise der Familie und mit Freunden. Starten Sie gut und erholt in das neue Jahr 2020!",
		"Deutschland ist ein offenes und gastfreundliches Land. Erfolg werden wir haben, wenn wir Frauen und Männer, die zu uns kommen, nicht nur als Arbeitskräfte sehen. Wir wollen, dass sie Teil unserer Gesellschaft sind. Heute beim #Fachkräftegipfel. #Fachkräfteeinwanderungsgesetz",
		"Herzlichen Glückwunsch zum 100. Geburtstag, liebe @AWOBund! Die starke Stimme für soziale Gerechtigkeit im Bund, Land und insbesondere in den Kommunen! Lasst uns als @spdde& @AWOBund weiterhin für eine bessere und gerechte Welt kämpfen.Auf die nächsten 100 Jahre!#awo100 #awo",
		"Das Wirtschaftswachstum zieht wieder an. Die expansive #Finanzpolitik des Bundes leistet dazu einen wichtigen Beitrag durch #Rekordinvestitionen, #Klimapaket und die Stärkung von kleinen und mittleren Einkommen um 25 Mrd. Euro. @ifo_Institut @BMF_Bund #Finanzen #Stabilitätsrat",
		"Ich halte #Cum-Ex für eine Riesenschweinerei. Und ich frage mich, wie irgendjemand diese Steuertricks für legal und legitim halten konnte. #transpareny  @gerhardschick",
		"Herzlichen Glückwunsch allen Mitgliedern des neugewählten Parteivorstands der @spdde.Wir stehen für den Zusammenhalt in unserem Land und für eine stärkere SPD. Dafür werden wir uns jetzt mit aller Kraft einsetzen. Gemeinsam.",
		"Die Mitglieder haben entschieden: Ich gratuliere @NowaboFM und @EskenSaskia zu ihrer Wahl. @klara_geywitz und ich haben kandidiert, um die SPD zu stärken. Es geht um den Zusammenhalt, in unserer Partei und in unserem Land. Die neue Führung hat meine Unterstützung. #spdgewinnt",
		"Diese kreative Unruhe, der Impuls, Gutes für Leute mit geringem Einkommen zu schaffen, das erwarten wir von Architektur und Stadtplanung. #bauhaus100 @BG_Museum",
		"Die Utopie nicht in der Vergangenheit zu sehen und die Zukunft nicht apokalyptisch zu beschreiben, sondern den Aufbruch zu wagen, mit all dem, was wir können – dafür steht Bauhaus bis heute. #bauhaus100 @BG_Museum Copyrights Catrin Schmitt #catrinschmitt_",
		"„Was heißt hier Haltung“? Im Rahmen von #bauhaus100 diskutiere ich diese Frage heute Abend in der Berlinischen Galerie u.a. mit SchülerInnen der Nelson Mandela Schule und der Paula Fürst Schule. @BG_Museum",
		"Der Bundestag hat den #Bundeshaushalt 2020 beschlossen 👍 #Klimaschutz #Infrastruktur #Forschung #Digitalisierung",
		// matteosalvinimi
		"Entro in edicola e cosa scopro? \"Salvini minacciato di morte\". Viva l’amore, la pace, la fratellanza... Avanti col sorriso, io non ho paura.💪😊",
		"Ieri a Vigarano Mainarda (Ferrara) con Paolo, ex tesserato Pd che non ha dubbi: il 26 gennaio sceglierà la Lega e #BorgonzoniPresidente! 😊 La strada è quella giusta, avanti tutta!!!#26gennaiovotoLega @BorgonzoniPres",
		"Stamattina a Soliera (Modena), il barbiere chiude il negozio per venire a salutarmi. Eccezionale, grazieee! 😄",
		"Un caffè al volo e si riparte! Ci vediamo tra poco a Possidonio (Mo), a Mirandola (Mo) alle 16.15 e a Modena a partire dalle 18. Chi si ferma è perduto!#26gennaiovotoLega #BorgonzoniPresidente @BorgonzoniPres",
		"Dai che il 26 gennaio liberiamo anche l'Emilia-Romagna, alla faccia di chi ci vuole male. #26gennaiovotoLega #BorgonzoniPresidente @BorgonzoniPres",
		"A parte la bufala su \"conti correnti in Svizzera\"😮, questo \"signore\" di Bologna aggiunge: \"DEVI MORIRE INFAME SCHIFOSO, in una stiva di immigrati che ti seviziano\". Ma quanto fa paura la Lega ? ",
		"Con Maya, splendida cagnolina con le idee ben chiare 😊🐶",
		"Come vedo una ruspa mi emoziono! Sentite che musica 🚜",
		"Arrivato ora a Carpi (Modena), l'affetto che sto ricevendo in questi giorni dagli emiliani è per me una ricompensa straordinaria, è questo l'unico sondaggio che conta. Si respira tanta voglia di cambiamento e di futuro. Il 26 gennaio anche qui si cambia, BASTA PD!",
		"Ma per il candidato del Pd (che si vergogna del suo simbolo) la colpa è della Lega! Roba da matti. Il 26 gennaio mandiamoli a casa! #26gennaiovotoLega #BorgonzoniPresidente @BorgonzoniPres",
		"A Finale Emilia (Modena), provata da terremoto, allagamenti e rischi ambientali: il Pd di Bonaccini vuole ampliare una discarica, ora sotto sequestro con vari indagati (tra cui l'ex sindaco di sinistra), mettendo in pericolo il lavoro degli agricoltori.",
		"In diretta dal mercato di Soliera (Modena), seguitemi! 🔴 LIVE 👉 https ://www.facebook.com/salviniofficial/videos/537854160139857/",
		"Un saluto da Finale Emilia (Modena)! #26gennaiovotoLega",
		// vonderleyen
		"We will invest all our energy into Europe🇪🇺and its people. #vdLcommission",
		"Merry Christmas to you and your families and a Happy New Year! ✨🎄💫 I wish you a peaceful end of 2019. May 2020 be a great year for Europe, and for every European.",
		"Un traité qui a donné une âme à l’Europe. Un traité qui a créé une Europe citoyenne. Un traité qui a remis les citoyens européens au cœur du projet européen. L’Europe c’est notre choix, que nous devons renouveler chaque jour, dans l’action.",
		"Democracy. The rule of law. Rights and liberties for all. Lisbon gave centre stage to the citizens of #Europe. #LisbonTreaty",
		"Courtesy call with @realDonaldTrump. Talked briefly about US-EU relations. I’m convinced, the close friendship and cooperation between Europe and the United States is crucial for mutual success. We both want a fair partnership. Look forward to meeting at the beginning of 2020.",
		"Congratulated @BorisJohnson on the phone for his electoral victory. We agreed to launch negotiations asap on future EU-UK partnership. We will meet at the beginning of 2020. The UK will always be a friend, partner and ally. 🇪🇺🇬🇧",
		"Yesterday, I presented the #EUGreenDeal. Today, I will discuss it intensively with the EU member states at #EUCO. It's in all our interest to turn climate & environmental challenges into opportunities across all policy areas and making the transition just and inclusive for all.",
		"Read the #EUGreenDeal's 50 actions for 2050 here👉 https://europa.eu/!fh78yC For a climate and nature friendly Europe.",
		"Many Europeans are already taking action. Our #EUGreenDeal is for them!",
		"Let's never forget what the cost of non-action would be: 👉River flooding costs our citizens over 5 bil / year 👉Our economy is losing almost 10 bil/year due to droughts We can resist these developments. With the road map for action, we make the transition cost fully sustainable.",
		"The #EUGreenDeal is not only about emissions. ➡️It's about boosting innovation. ➡️It's about quality food. ➡️It's about modern mobility. It will create new businesses & markets all across 🇪🇺. The #EUGreenDeal is our new growth strategy. It is not consuming but it gives back.",
		"The #EUGreenDeal is more than just a vision. It is a roadmap for action. It has 50 actions for 2050 – for a climate and nature friendly Europe. Our goal is to reconcile our economy with our planet, and make it work for our people. This is Europe's 'man on the moon' moment.",
		"👇🏻",
		// MaireadMcGMEP
		"Delighted to meet the young women behind @iCutKe and hear about their work on #endFMG - my thanks to colleague @Assita_Kanko for bringing their work to my attention 👏👏",
		"Chairing @europarl_en debate on conclusions of December #EUCO #climate #MFF #Brexit",
		"First debate this morning @Europarl_EN",
		"Chairing the final #EPlenary debates of the day on animal welfare, and the digital transformation of health and care",
		"Coming up on @Channel4News with @mattfrei from #Strasbourg on #Brexit #nextsteps",
		"Debate on #pollinators starting now  @Europarl_EN 🐝 🐜 🕷 🐞",
		"Joining @BBCNews @BBCSimonMcCoy soon from @Europarl_EN on #Brexit #nextsteps",
		"Speaking to @BBCWorldatOne shortly from #Strasbourg #Brexit",
		"Results of @EUombudsman first vote 240 votes @EUOmbudsmanEOR 👏 second vote tomorrow....",
		"Chairing this morning’s #EPlenary debate on the rule of law in Malta #DaphneCaruanaGalizia",
		"Debate now @Europarl_EN #RuleOfLaw #Malta",
		"With @BBCNews talking #Brexit #ElectionResults2019 from @Europarl_EN",
		"Live now @LMFMRADIO discussing #Brexit #UKElection",
		// EP_President
		"Glückwünsche an @sebastiankurz zu seiner erneuten Ernennung als Bundeskanzler Österreichs. Ich freue mich darauf, mit ihm und seiner neuen Regierung an einer grünen und pro-europäischen Agenda zu arbeiten.",
		"Enhorabuena al presidente @sanchezcastejon por su reelección y traslado mis mejores deseos para su nuevo Gobierno. España es un socio clave en la UE, trabajaremos juntos en esta nueva etapa y continuaremos nuestra estrecha colaboración por una Europa más justa, verde y social.",
		"Il mio augurio per queste feste è un augurio di libertà, dignità e solidarietà. Tanti auguri a tutte e a tutti! Tanti auguri all’Europa!",
		"My wish for these holidays is one of freedom, dignity and solidarity. Best wishes to all! Best wishes to our Europe!",
		"The ECJ found that a person elected acquires the status of member of the @Europarl_EN and therefore enjoys immunity. I call upon the competent Spanish authorities to align with the ruling. I have given a mandate to the services to evaluate its possible impact on the composition.",
		"Congratulations to Emily O’Reilly on her reappointment as @EUombudsman. I look forward to working with her to increase transparency in the EU institutions and build citizens’ trust.",
		"Ilham Tohti’s fight for human rights shows the importance of dialogue, reconciliation and mutual understanding. The same values that underpin the European project and this Parliament. We call for his immediate and unconditional release. http://eptwitter.eu/qmGy  #SakharovPrize",
		"🔴LIVE: We are honoured to have Ilham Tohti’s daughter, Jewher Ilham, representing him today and receiving the 2019 #SakharovPrize for freedom of thought on his behalf. Follow the press conference ↓",
		"He is serving a life sentence for working tirelessly to defend the rights of China’s Uyghur minority. Today, Ilham Tohti won’t be able to receive the 2019 #SakharovPrize, but his voice will resound in the @Europarl_EN. Follow the ceremony LIVE↓",
		"The #LisbonTreaty has strengthened human dignity, equality, democracy, solidarity and the rule of law, pillars on which the EU was founded. 10 years after this pivotal moment, we must keep looking at new ideas for our future together. Read more → http://eptwitter.eu/qmEb",
		"Our Union should be one built on humanity and inclusion. In the complex debate on migration, the @Europarl_EN will continue to represent the voice of solidarity. #MigrantsDay",
		"Congratulations to @BorisJohnson on his success in yesterday's vote. We now expect the UK Parliament to quickly approve the agreement with the EU to allow an orderly Brexit by 31 Jan. Once it has done so, the @Europarl_EN stands ready to vote on it.",
		"The next few years will be decisive for the future of Europe. We have no margin for error. We need to address citizens most pressing concerns and ensure we have the means to do so. Full speech → http://eptwitter.eu/qm7B  #EUCO"
	};
};